spring.application.name=booking-service

# Live Aiven Cloud Database Configurations
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-7a7f489-roomreserve.l.aivencloud.com:23678/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect